### ISSUE TITLE
Broom and fit_issf

### ISSUE THREAD

**Issue by pntoiv** [jmsigner/amt#114]
Hey,

is there a way to use tidy() (from Broom) with clogit objects returned by fit_issf?

Broom has compatibility with clogit() but tidy() doesn't recoqnize the model objects returned by amt package's fit_issf.

**Comment by bmrishabh** [comment]
Hi @pntoiv , I am not a contributor to this package but here is a quick response since you have posted recently and I happened to come accross it.

The object returned by fit_issf is a list of three objects: the model fit, the step length distribution, and the turn angle distribution. The tidy() function should recognise the "model" part of this object. For example, if `your_model <- fit_issf(data)` then `tidy(your_model$model)` should give you the desired output.

**Comment by jmsigner** [comment]
Thanks @bmrishabh  that's how it works at the momeent.
